// Vigils
// export const INITIALIZE_VIGILS = "INITIALIZE_VIGILS";
export const INITIALIZE_SHIFTS = "INITIALIZE_SHIFTS";
export const INITIALIZE_USERS = "INITIALIZE_USERS";
export const INITIALIZE_USER = "INITIALIZE_USER";
export const INITIALIZE_DISCUSSIONS = "INITIALIZE_DISCUSSIONS";
export const INITIALIZE_HISTORY = "INITIALIZE_HISTORY";
// export const ADD_VIGIL = "ADD_VIGIL";
// export const EDIT_VIGIL = "EDIT_VIGIL";
// export const DELETE_VIGIL = "DELETE_VIGIL";
export const ADD_DISCUSSION = "ADD_DISCUSSION";
export const EDIT_DISCUSSION = "EDIT_DISCUSSION";
export const DELETE_DISCUSSION = "DELETE_DISCUSSION";
export const ADD_SHIFT = "ADD_SHIFT";
export const DELETE_SHIFT = "DELETE_HISTORY_SHIFT";
export const ADD_HISTORY_SHIFT = "ADD_HISTORY_SHIFT";
export const DELETE_HISTORY_SHIFT = "DELETE_HISTORY_SHIFT";
