// Vigils
export const INITIALIZE_VIGILS = 'INITIALIZE_VIGILS';
export const INITIALIZE_USERS = 'INITIALIZE_USERS';
export const INITIALIZE_USER = 'INITIALIZE_USER';
export const INITIALIZE_DISCUSSIONS = 'INITIALIZE_DISCUSSIONS';
export const INITIALIZE_HISTORY = 'INITIALIZE_HISTORY';
